export const BASE_RECTANGLE_WIDTH = 100;
export const BASE_RECTANGLE_HEIGHT = 50;
export const MIN_RECTANGLE_WIDTH = 60;
export const MIN_RECTANGLE_HEIGHT = 30;
export const RECTANGLE_MAX_CHARACTERS = 35;
export const PIXELS_PER_CHARACTER = 9.5;
export const PERCENTAGE_INCREMENT = 0.01;
